/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import java.net.URL;
import java.net.HttpURLConnection;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	// begin code from https://www.baeldung.com/java-check-url-exists
    	URL url = new URL(args[0]);
    	//URLConnection urlCon = url.openConnection();
    	HttpURLConnection urlCon = (HttpURLConnection) url.openConnection();
    	urlCon.setRequestMethod("HEAD");
    	 
    	int responseCode = urlCon.getResponseCode();
    	//end code from https://www.baeldung.com/java-check-url-exists
    	
        if (urlCon.HTTP_NOT_FOUND ==  responseCode) {
            System.err.println("Invalid inout");
            System.exit(1);
        }
        
        System.out.println(new App().getGreeting());
        
    }
}
