/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.net.HttpURLConnection;


public class RunProjections {
    public String getGreeting() {
        return "Hello World!";
    }

    public URL getURL(String urlStr){
        // begin code from https://www.baeldung.com/java-check-url-exists
        URL url;
        int responseCode;
        try {
            url = new URL(urlStr);
        } catch (MalformedURLException e) {
            e.printStackTrace();
            return null;
        }

        //URLConnection urlCon = url.openConnection();
        HttpURLConnection urlCon = null;

        try {
            urlCon = (HttpURLConnection) url.openConnection();
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            urlCon.setRequestMethod("HEAD");
        } catch (ProtocolException e) {
            e.printStackTrace();
            System.exit(1);
        }

        try {
            responseCode = urlCon.getResponseCode();
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }

        //end code from https://www.baeldung.com/java-check-url-exists

        if (urlCon.HTTP_NOT_FOUND ==  responseCode) {
            System.err.println("Invalid inout");
            return null;
        }
        return url;
    }

    public static void main(String[] args) {
        RunProjections prog = new RunProjections();
        URL url = prog.getURL(args[0]);
        System.out.println(prog.getGreeting());
    }
}
