/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RunProjectionsTest {
    @Test void appHasAGreeting() {
        RunProjections classUnderTest = new RunProjections();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
